INSERT INTO Job(title, description) VALUES
('The Great Gatsby', 'A novel by F. Scott Fitzgerald set in the Roaring Twenties.'),
('To Kill a Mockingbird', 'A Pulitzer Prize-winning novel by Harper Lee.'),
('1984', 'A dystopian novel by George Orwell.'),
('Pride and Prejudice', 'A novel by Jane Austen about the Bennett sisters and their search for love.'),
('The Catcher in the Rye', 'A novel by J.D. Salinger about a young man named Holden Caulfield.'),
('The Lord of the Rings', 'A high fantasy novel by J.R.R. Tolkien.'),
('Brave New World', 'A dystopian novel by Aldous Huxley.'),
('Moby-Dick', 'A novel by Herman Melville about Captain Ahab and his obsession with a white whale.'),
('Jane Eyre', 'A novel by Charlotte Bronte about a governess and her romance with her employer.'),
('The Picture of Dorian Gray', 'A novel by Oscar Wilde about a man who sells his soul for eternal youth.'),
('Heart of Darkness', 'A novella by Joseph Conrad about a journey up the Congo River.'),
('Fahrenheit 451', 'A dystopian novel by Ray Bradbury about a society where books are banned.'),
('Wuthering Heights', 'A novel by Emily Bronte about the passionate love between Heathcliff and Catherine.'),
('The Adventures of Huckleberry Finn', 'A novel by Mark Twain about a boy and a slave who journey down the Mississippi River.'),
('The Odyssey', 'An epic poem by Homer about the Greek hero Odysseus and his journey home after the Trojan War.'),
('The Road', 'A post-apocalyptic novel by Cormac McCarthy about a father and son traveling through a ravaged landscape.'),
('One Hundred Years of Solitude', 'A novel by Gabriel Garcia Marquez about the Buendia family and the town of Macondo.'),
('The Color Purple', 'A novel by Alice Walker about a young black woman named Celie.'),
('The Bell Jar', 'A novel by Sylvia Plath about a young woman named Esther Greenwood and her descent into mental illness.'),
('A Clockwork Orange', 'A dystopian novel by Anthony Burgess about a violent youth named Alex.'),
('Slaughterhouse-Five', 'A novel by Kurt Vonnegut about the bombing of Dresden.'),
('Gone with the Wind', 'A novel by Margaret Mitchell about the American Civil War and its aftermath.'),
('The Sun Also Rises', 'A novel by Ernest Hemingway about a group of American and British expatriates in Paris.'),
('The Handmaid Tale', 'A dystopian novel by Margaret Atwood about a society where women are oppressed and used for reproduction.'),
('The Grapes of Wrath', 'A novel by John Steinbeck about the Joad family and their journey to California during the Great Depression.');